[__config__]
max_concurrency = 1

[LINUX_KERNEL]
source = "git"
git = "https://github.com/archlinux/linux.git"
include_regex = 'v\d+(\.\d+)*-arch\d+'
from_pattern = '-([a-z])'
to_pattern = '.\1'
prefix = "v"

[TINYCC]

[MUSL]
source = "git"
git = "https://git.musl-libc.org/git/musl"
prefix = "v"

[_OKSH]
source = "git"
git = "https://github.com/ibara/oksh.git"
include_regex = "oksh-(.+)"
prefix = "oksh-"

[SBASE]
source = "git"
git = "git://git.suckless.org/sbase"
use_commit = true
from_pattern = "(.{5,5}).*"
to_pattern = '\1'
use_tag = false

[UBASE]
source = "git"
git = "git://git.suckless.org/ubase"
use_commit = true
from_pattern = "(.{5,5}).*"
to_pattern = '\1'
use_tag = false

[SMDEV]
source = "git"
git = "git://git.suckless.org/smdev"
use_commit = true
from_pattern = "(.{5,5}).*"
to_pattern = '\1'
use_tag = false

[SINIT]
source = "git"
git = "git://git.suckless.org/sinit"
use_commit = true
from_pattern = "(.{5,5}).*"
to_pattern = '\1'
use_tag = false

[SDHCP]
source = "git"
git = "git://git.2f30.org/sdhcp"
use_commit = true
from_pattern = "(.{5,5}).*"
to_pattern = '\1'
use_tag = false

[UFLBBL]
source = "git"
git = "https://github.com/andreasbaumann/uflbbl.git"
branch = "master"
use_commit = true
from_pattern = "(.{7,7}).*"
to_pattern = '\1'
use_tag = false

[LIBEVENT]
source = "github"
github = "libevent/libevent"
use_latest_release = true
prefix = "release-"

[VIS]
source = "git"
git = "https://github.com/martanne/vis.git"
branch = "master"
use_commit = true
from_pattern = "(.{7,7}).*"
to_pattern = '\1'
use_tag = false

[LIBTERMKEY]

[NETBSD_NCURSES]
source = "github"
github = "sabotage-linux/netbsd-curses"
use_latest_release = true
prefix = "v"

[TMUX]
source = "github"
github = "tmux/tmux"
use_latest_release = true

[ZLIB]
source = "git"
git = "https://github.com/madler/zlib.git"
prefix = "v"

[MANDOC]
source = "regex"
url = "https://mandoc.bsd.lv/"
regex = 'current version (\d+\.\d+\.\d+) '

[ABASE]
source = "git"
git = "https://github.com/andreasbaumann/abase.git"
branch = "master"
use_commit = true
from_pattern = "(.{7,7}).*"
to_pattern = '\1'
use_tag = false

[NBD]
source = "github"
github = "NetworkBlockDevice/nbd"
use_latest_release = true
prefix = "nbd-"

[SAMURAI]
source = "git"
git = "https://github.com/michaelforney/samurai.git"
use_latest_release = true

[MUON]
source = "git"
git = "https://github.com/muon-build/muon.git"
use_latest_release = true

[JOE]
source = "regex"
url = "https://joe-editor.sourceforge.io/"
regex = 'Latest version: (\d+\.\d+)'

[DROPBEAR]
source = "github"
github = "mkj/dropbear"
use_latest_release = true
prefix = "DROPBEAR_"

[TINYXLIB]

[TINYXSERVER]

[BDFTOPCF]

[FONT_CURSOR_MISC]
[FONT_MISC_MISC]
[FONT_UTIL]

[RXVT]

[XHOST_VERSION]
source = "gitlab"
gitlab = "xorg/app/xhost"
host = "gitlab.freedesktop.org"
use_max_tag = true
include_regex = ".*xhost-.*"
prefix = "xhost-"

[XAUTH]
source = "gitlab"
gitlab = "xorg/app/xauth"
host = "gitlab.freedesktop.org"
include_regex = ".*xauth-.*"
use_max_tag = true
prefix = "xauth-"

[MEH]
source = "git"
git = "https://github.com/andreasbaumann/meh.git"
branch = "integration"
use_commit = true
from_pattern = "(.{7,7}).*"
to_pattern = '\1'
use_tag = false

[SLOCK]
source = "git"
git = "git://git.suckless.org/slock"
branch = "master"
use_commit = true
from_pattern = "(.{7,7}).*"
to_pattern = '\1'
use_tag = false

[LUA]
source = "regex"
regex = "lua-(5.1.\\d+).tar.gz"
url = "https://www.lua.org/ftp/"

[NOTION]

[WORDGRINDER]
source = "git"
git = "https://github.com/davidgiven/wordgrinder.git"
branch = "master"
use_tag = true

[SC]

[MUTT]
source = "git"
git = "https://gitlab.com/muttmua/mutt.git"
exclude_regex = ".*(muttintl|patch).*"
from_pattern = 'mutt-(\d+)-(\d+)-(\d+)-rel'
to_pattern = '\1.\2.\3'

[FBSET]

[LBFORTH]
source = "git"
git = "https://github.com/DosWorld/lbforth.git"
branch = "master"
use_commit = true
from_pattern = "(.{7,7}).*"
to_pattern = '\1'
use_tag = false

[SQLITE]
source = "regex"
regex = "Version (\\d+.\\d+.\\d+)"
url = "https://www.sqlite.org/index.html"
