[__config__]
max_concurrency = 1

[LINUX_KERNEL]
source = "git"
git = "https://github.com/archlinux/linux.git"
include_regex = 'v\d+(\.\d+)*-arch\d+'
from_pattern = '-([a-z])'
to_pattern = '.\1'
prefix = "v"

[TINYCC]
source = "git"
git = "https://repo.or.cz/tinycc.git"
use_commit = true
from_pattern = "(.{5,5}).*"
to_pattern = '\1'
use_tag = false

[MUSL]
source = "git"
git = "https://git.musl-libc.org/git/musl"
prefix = "v"

[_OKSH]
source = "git"
git = "https://github.com/ibara/oksh.git"
include_regex = "oksh-(.+)"
prefix = "oksh-"

[SBASE]
source = "git"
git = "git://git.suckless.org/sbase"
use_commit = true
from_pattern = "(.{5,5}).*"
to_pattern = '\1'
use_tag = false

[UBASE]
source = "git"
git = "git://git.suckless.org/ubase"
use_commit = true
from_pattern = "(.{5,5}).*"
to_pattern = '\1'
use_tag = false

[SMDEV]
source = "git"
git = "git://git.suckless.org/smdev"
use_commit = true
from_pattern = "(.{5,5}).*"
to_pattern = '\1'
use_tag = false

[SINIT]
source = "git"
git = "git://git.suckless.org/sinit"
use_commit = true
from_pattern = "(.{5,5}).*"
to_pattern = '\1'
use_tag = false

[SDHCP]
source = "git"
git = "git://git.2f30.org/sdhcp"
use_commit = true
from_pattern = "(.{5,5}).*"
to_pattern = '\1'
use_tag = false

[UFLBBL]
source = "git"
git = "https://github.com/andreasbaumann/uflbbl.git"
branch = "master"
use_commit = true
from_pattern = "(.{7,7}).*"
to_pattern = '\1'
use_tag = false

[LIBEVENT]
source = "github"
github = "libevent/libevent"
use_latest_release = true
prefix = "release-"

[VIS]
source = "git"
git = "https://github.com/martanne/vis.git"
branch = "master"
use_commit = true
from_pattern = "(.{7,7}).*"
to_pattern = '\1'
use_tag = false

[KILO]
source = "git"
git = "https://github.com/antirez/kilo.git"
branch = "master"
use_commit = true
from_pattern = "(.{7,7}).*"
to_pattern = '\1'
use_tag = false

[LIBTERMKEY]
source = "regex"
url = "https://www.leonerd.org.uk/code/libtermkey/"
regex = 'libtermkey-(\d+\.\d+).tar.gz'

[NETBSD_NCURSES]
source = "github"
github = "sabotage-linux/netbsd-curses"
use_latest_release = true
prefix = "v"

[TMUX]
source = "github"
github = "tmux/tmux"
use_latest_release = true

[ZLIB]
source = "regex"
url = "https://www.zlib.net/"
regex = 'version (\d+\.\d+\.\d+)'

[MANDOC]
source = "regex"
url = "https://mandoc.bsd.lv/"
regex = 'current version (\d+\.\d+\.\d+) '

[ABASE]
source = "git"
git = "https://github.com/andreasbaumann/abase.git"
branch = "master"
use_commit = true
from_pattern = "(.{7,7}).*"
to_pattern = '\1'
use_tag = false

[NBD]
source = "github"
github = "NetworkBlockDevice/nbd"
use_latest_release = true
prefix = "nbd-"

[SAMURAI]
source = "git"
git = "https://github.com/michaelforney/samurai.git"
use_latest_release = true

[MUON]
source = "git"
git = "https://github.com/muon-build/muon.git"
use_latest_release = true

[JOE]
source = "regex"
url = "https://joe-editor.sourceforge.io/"
regex = 'Latest version: (\d+\.\d+)'

[DROPBEAR]
source = "github"
github = "mkj/dropbear"
use_latest_release = true
prefix = "DROPBEAR_"

[TINYXLIB]
source = "git"
git = "https://github.com/idunham/tinyxlib.git"
branch = "master"
use_commit = true
from_pattern = "(.{7,7}).*"
to_pattern = '\1'
use_tag = false

[TINYXSERVER]
source = "git"
git = "https://github.com/idunham/tinyxserver.git"
branch = "master"
use_commit = true
from_pattern = "(.{7,7}).*"
to_pattern = '\1'
use_tag = false

[BDFTOPCF]
source = "regex"
url = "https://xorg.freedesktop.org/archive/individual/util/"
regex = 'bdftopcf-(\d+\.\d+.\d+).tar.gz'

[FONT_CURSOR_MISC]
source = "regex"
url = "https://www.x.org/archive/individual/font/"
regex = 'font-cursor-misc-(\d+\.\d+.\d+).tar.gz'

[FONT_MISC_MISC]
source = "regex"
url = "https://www.x.org/archive/individual/font/"
regex = 'font-misc-misc-(\d+\.\d+.\d+).tar.gz'

[FONT_UTIL]
source = "regex"
url = "https://www.x.org/archive/individual/font/"
regex = 'font-util-(\d+\.\d+.\d+).tar.gz'

[RXVT]
source = "regex"
url = "https://sourceforge.net/projects/rxvt/files/rxvt/"
regex = '/projects/rxvt/files/rxvt/(\d+\.\d+.\d+)/'

[XHOST]
source = "regex"
url = "https://www.x.org/archive/individual/app/"
regex = 'xhost-(\d+\.\d+.\d+).tar.gz'

[XAUTH]
source = "regex"
url = "https://www.x.org/archive/individual/app/"
regex = 'xauth-(\d+\.\d+.\d+).tar.gz'

[MEH]
source = "git"
git = "https://github.com/andreasbaumann/meh.git"
branch = "integration"
use_commit = true
from_pattern = "(.{7,7}).*"
to_pattern = '\1'
use_tag = false

[SLOCK]
source = "git"
git = "git://git.suckless.org/slock"
branch = "master"
use_commit = true
from_pattern = "(.{7,7}).*"
to_pattern = '\1'
use_tag = false

[LUA]
source = "regex"
regex = "lua-(5.1.\\d+).tar.gz"
url = "https://www.lua.org/ftp/"

[NOTION]
source = "git"
git = "https://github.com/raboof/notion.git"
branch = "master"
include_regex = "(3-\\d+)"
use_tag = true
use_commit = false
#NOTION_VERSION="435631f"3-2019050101

[WORDGRINDER]
source = "git"
git = "https://github.com/davidgiven/wordgrinder.git"
branch = "master"
use_tag = true

[SC]
source = "github"
github = "n-t-roff/sc"
use_latest_release = true

[MUTT]
source = "git"
git = "https://gitlab.com/muttmua/mutt.git"
exclude_regex = ".*(muttintl|patch).*"
from_pattern = 'mutt-(\d+)-(\d+)-(\d+)-rel'
to_pattern = '\1.\2.\3'

[FBSET]
source = "regex"
url = "https://src.fedoraproject.org/repo/pkgs/fbset/"
regex = "fbset-(\\d+.\\d+).tar.gz"

[LBFORTH]
source = "git"
git = "https://github.com/DosWorld/lbforth.git"
branch = "master"
use_commit = true
from_pattern = "(.{7,7}).*"
to_pattern = '\1'
use_tag = false

[SQLITE]
source = "regex"
regex = "Version (\\d+.\\d+.\\d+)"
url = "https://www.sqlite.org/index.html"

[NASM]
source = "git"
git = "https://github.com/netwide-assembler/nasm.git"
include_regex = "nasm-[\\d\\.]+"
prefix = "nasm-"

[PYTHON]
source = "git"
git = "https://github.com/python/cpython.git"
prefix = "v"
include_regex = "^v3\\.8\\.[0-9]+$"
exclude_regex = ".*(a|b|rc).*"
